services:
  db:
    build:
      context: .
      dockerfile: mysql/Dockerfile
    platform: linux/amd64
    container_name: demo_wave_mysql
    ports:
      - "3310:3306"
    environment:
      MYSQL_ROOT_PASSWORD: mysql
      MYSQL_DATABASE: demo_wave
      MYSQL_USER: rikuganeko
      MYSQL_PASSWORD: Riku1204
      TZ: Asia/Tokyo
    volumes:
      - demo_wave_db_data:/var/lib/mysql

volumes:
  demo_wave_db_data:  # ボリュームを定義